apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp
        image: springapp:latest
        imagePullPolicy: Never # 외부 레지스트리에서 이미지를 가져오지 않도록 설정
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"  # CPU 리미트 줄이기
          requests:
            memory: "64Mi"
            cpu: "200m"  # CPU 요청 줄이기
        ports:
        - containerPort: 8899
